logging:
  level:
    root: info

server:
  port: 8885

spring:
  application:
    name:
      user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/mealtime-user-service-db
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: off
  sql:
    init:
      mode: always
  mvc:
    format:
      date-time: dd-MM-yyyy HH:mm:ss
  web:
    resources:
      static-locations: classpath:/resources, classpath:/resources/**, classpath:/db/


admin:
  password: 997100ed-9f34-4eca-9471-ef09ca0b1cfa
  encode: $2a$05$paMdtfwh3x2pyGlaA5w.G.UaEqLpyx5os4vF9nuk9YCET2oh1.Tqm
user:
  password: 12345
  encode: $2a$05$t9QYvnHZj8yY32gwX6WW2eGcT1Zp7R3CBUgappVpU1LXkDxTzENJ6